[[main]]
name = "Home"
url = "/"
weight = 100
pre = "icon-home"
[[main]]
name = "Portfolio"
url = "/portfolio/"
weight = 200
pre = "icon-picture"
[[main]]
name = "Get In Touch"
url = "/contact/"
weight = 500
pre = "icon-envelope"
[[main]]
name = "Feisty Fairies"
parent = "Portfolio"
url = "/portfolio/feisty-fairies/"
weight = 100
[[main]]
name = "Felted Flock"
parent = "Portfolio"
url = "/portfolio/felted-flock/"
weight = 200
[[main]]
name = "Quilts and Cushions"
parent = "Portfolio"
url = "/portfolio/quilts-and-cushions/"
weight = 300