[[main]]
name = "Home"
url = "/"
weight = 100
pre = "icon-home"
[[main]]
name = "Portfolio"
url = "/categories/"
weight = 200
pre = "icon-picture"
[[main]]
name = "Get In Touch"
url = "/contact/"
weight = 500
pre = "icon-envelope"
[[main]]
name = "Feisty Fairies"
parent = "Portfolio"
url = "/categories/feisty-fairies/"
weight = 100
[[main]]
name = "Felted Flock"
parent = "Portfolio"
url = "/categories/felted-flock/"
weight = 200
[[main]]
name = "Quilts and Cushions"
parent = "Portfolio"
url = "/categories/Quilts and Cushions/"
weight = 300