name = "html5up-story"
homepage = "https://github.com/littleorangeweb"
license = "Creative Commons 3.0"
licenselink = "http://creativecommons.org/licenses/by/3.0/"

tags = []
features = []
min_version = "0.41.0"

[author]
  name = "littleorangeweb"
  homepage = "https://github.com/littleorangeweb"

# If porting an existing theme
[original]
  name = "html5up"
  homepage = "https://html5up.net"
  repo = "https://html5up.net/story"