backend:
  name: git-gateway
  branch: main # Branch to update

media_folder: "assets/img/uploads"
public_folder: "/media/uploads"

collections:
  - name: "feisty-fairies" # Used in routes
    label: "Feisty Fairies" # Used in the UI
    folder: "content/portfolio" # The path to Dir folder
    filter: {field: "category", value: "Feisty Fairies"}
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{slug}}" # Filename template
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Feisty Fairies", "Felted Flock"]
      - label: "Main Image"
        name: "image"
        widget: "object"
        required: false
        fields:
        - {label: "Image", name: "path", widget: "image"}
        - {label: "alt text", name: "alt", widget: "string"}
      - {label: "Media", name: "media", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: "true"}
  - name: "felted-flock" # Used in routes
    label: "Felted Flock" # Used in the UI
    folder: "content/portfolio" # The path to Dir folder
    filter: {field: "category", value: "Felted Flock"}
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{slug}}" # Filename template
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - label: "Category"
        name: "category"
        widget: "select"
        options: ["Feisty Fairies", "Felted Flock"]
      - label: "Main Image"
        name: "image"
        widget: "object"
        required: false
        fields:
        - {label: "Image", name: "path", widget: "image"}
        - {label: "alt text", name: "alt", widget: "string"}
      - {label: "Media", name: "media", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: "true"}