backend:
  name: git-gateway
  branch: static-site-version # Branch to update

media_folder: "static/images/uploads" # Media files stored in repo
public_folder: "/images/uploads" # Base URL for uploaded media src attributes

display_url: https://determined-neumann-138ba9.netlify.app
publish_mode: editorial_workflow

collections:
  - label: Feisty Fairies
    name: feisty-fairies
    folder: "content/portfolio/feisty-fairies"
    preview_path: "/portfolio/feisty-fairies/{{filename}}"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Main image, name: image, widget: object, required: false, fields: [
          {label: Image, name: path, widget: image},
          {label: alt-text, name: alt, widget: string}]}
      - {label: Body, name: body, widget: markdown}
      - {label: Gallery, name: gallery, widget: list, required: false, label_singular: Image, summary: '{{fields.alt}}', collapsed: true, fields: [
          {label: Image, name: path, widget: image},
          {label: Title, name: alt, widget: string}]}
      - {label: Date, name: date, widget: datetime}
  - label: Felted Flock
    name: felted-flock
    folder: "content/portfolio/felted-flock"
    preview_path: "/portfolio/felted-flock/{{filename}}"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Main image, name: image, widget: object, required: false, fields: [
          {label: Image, name: path, widget: image},
          {label: alt-text, name: alt, widget: string}]}
      - {label: Body, name: body, widget: markdown}
      - {label: Gallery, name: gallery, widget: list, required: false, label_singular: Image, summary: '{{fields.alt}}', collapsed: true, fields: [
          {label: Image, name: path, widget: image},
          {label: Title, name: alt, widget: string}]}
      - {label: Date, name: date, widget: datetime}
  - label: Quilts and Cushions
    name: quilts-and-cushions
    folder: "content/portfolio/quilts-and-cushions"
    preview_path: "/portfolio/quilts-and-cushions/{{filename}}"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Main image, name: image, widget: object, required: false, fields: [
          {label: Image, name: path, widget: image},
          {label: alt-text, name: alt, widget: string}]}
      - {label: Body, name: body, widget: markdown}
      - {label: Gallery, name: gallery, widget: list, required: false, label_singular: Image, summary: '{{fields.alt}}', collapsed: true, fields: [
          {label: Image, name: path, widget: image},
          {label: Title, name: alt, widget: string}]}
      - {label: Date, name: date, widget: datetime}
  - name: pages
    label: Pages
    files:
      - file: "content/_index.md"
        label: Home Page
        name: home
        editor:
          preview: false
        fields:
        - {label: Title, name: title, widget: string}
        - {label: Subtitle, name: subtitle, widget: string, required: false}
        - {label: Main image, name: image, widget: object, required: false, collapsed: true, fields: [
          {label: Image, name: path, widget: image},
          {label: alt-text, name: alt, widget: string}]}
        - label: About
          name: about
          widget: object
          fields:
            - label: Heading
              name: title
              widget: string
            - label: Body
              name: body
              widget: markdown
        - {label: Date, name: date, widget: datetime,}
      - file: "content/portfolio/_index.md"
        label: Portfolio Page
        name: portfolio
        editor:
          preview: false
        fields:
        - {label: Title, name: title, widget: string}
        - {label: Subtitle, name: subtitle, widget: string, required: false}
        - {label: Body, name: body, widget: markdown}
        - {label: Date, name: date, widget: datetime, hidden: true}
      - file: "content/contact/_index.md"
        label: Contact Page
        name: contact
        editor:
          preview: false
        fields:
        - {label: Title, name: title, widget: string}
        - {label: Subtitle, name: subtitle, widget: string, required: false}
        - {label: Body, name: body, widget: markdown}
        - {label: Date, name: date, widget: datetime, hidden: true}
