name = "html5up-story"
homepage = "https://github.com/littleorangeweb"
license = "Creative Commons 3.0"
licenselink = "https://github.com/littleorangeweb/annestewarttextiles/themes/html5up-story/license.txt"

tags = []
features = []
min_version = "0.41.0"

[author]
  name = "littleorangeweb"
  homepage = "https://github.com/littleorangeweb"

[original]
  name = "html5up"
  homepage = "https://html5up.net"
  repo = "https://html5up.net/story"